name: Leibo
favicon: null
layout_spectrum: 0.25358
typography_spectrum: 0.90839
title: My favorite scientists in this whole universe and any parallell  ones too
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#281f18'
    - '#bbb8b1'
    - '#7c523a'
    - '#967353'
    - '#e5e6e1'
  brandStrength: 0
  lightness: 0.8842448126524687
  saturation: 0.6905633104033768
  rhythmicContrast: 0.698808460496366
purpose: []
