name: leibo
favicon: null
layout_spectrum: 0.19013609737157822
typography_spectrum: 0.25062426016665995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.455966183450073
  lightness: 0.8842448126524687
  saturation: 0.6905633104033768
  rhythmicContrast: 0.698808460496366
purpose: []
